### ISSUE TITLE
Rename Object folder to Utilities

### ISSUE THREAD

**Issue by joshcalafell** [rabbitfighter81/WordSleuth-Android#10]
Rename Object folder to Utilities

**Comment by redragonx** [comment]
Utils already exist, so use that.

**Comment by joshcalafell** [comment]
My suggestions are to keep these three classes alone, so alternate folder names could be WordItems, WordTypes, Words, something like that.

**Comment by joshcalafell** [comment]
![entry](https://cloud.githubusercontent.com/assets/6219922/8508707/f1fb0acc-2237-11e5-98e1-8cbb867fe0e8.png)

I changed the directory name from Objects/ (which Stephen rightly thought was vague and confusing) to Entries/ according to the second definition of the word in the above picture. I think this clearly indicates the type of objects kept in this subdirectory
