### ISSUE TITLE
Remove unnecessary and unused code

### ISSUE THREAD

**Issue by joshcalafell** [rabbitfighter81/WordSleuth-Android#11]
There are unnecessary classes and code.

**Comment by joshcalafell** [comment]
I removed MyQuery.java because it was not used, and some legacy code that was also unused.

**Comment by joshcalafell** [comment]
Reopened until I feel it's actually completed.

**Comment by joshcalafell** [comment]
Copy and paste all removed code below and give class name plz 😀

**Comment by redragonx** [comment]
This is legacy code. This is in searchactivity.java Please use fragment manager.

```
// Array to hold fragment states
public Fragment[] frags = new Fragment[] // [0x0,0x1,0x2]
        {new SearchInputFragment(),new SearchLoadingFragment(),new SearchResultsFragment()};
```

**Comment by joshcalafell** [comment]
There's no more unused code except Combo.java which we may or may not ever use
