### ISSUE TITLE
Bug - Query not being reset when a new search is submitted (see photo)

### ISSUE THREAD

**Issue by joshcalafell** [rabbitfighter81/WordSleuth-Android#13]
In this photo, I searched for "testing", got correct results, and then searched again for "Bryancoulter" (a freinds name with cool anagrams btw) and the query text did not get reset. 

![screenshot_2015-07-04-11-16-00](https://cloud.githubusercontent.com/assets/6219922/8508845/0dbb0774-223f-11e5-86fe-de9d6373679a.png)

**Comment by joshcalafell** [comment]
This is anoying me :(

**Comment by redragonx** [comment]
Try it now :) :+1:

**Comment by joshcalafell** [comment]
Great. We can mark this as closed.
