### ISSUE TITLE
All devs should switch to OracleJDK instead of OpenJDK for this project

### ISSUE THREAD

**Issue by joshcalafell** [rabbitfighter81/WordSleuth-Android#14]
All devs should switch to OracleJDK instead of OpenJDK for this project, to make sure there are no issues with android-studio

**Comment by joshcalafell** [comment]
I still need to do this. All developers please respond when done.

**Comment by joshcalafell** [comment]
I switched, also I don't think it's a huge deal. Mostly for the emulator.

**Comment by redragonx** [comment]
FYI, the emulator does not run in java at all, but the IDE does and Grandle as well.
