### ISSUE TITLE
Add splash screen and think about loading dict into a database during load.

### ISSUE THREAD

**Issue by joshcalafell** [rabbitfighter81/WordSleuth-Android#16]
Moving through a do using cursors may be faster than doing the search how it's done now. I have a few ideas but we should plan.

**Comment by redragonx** [comment]
We should erase the text files on the very first start of the app to create the db

**Comment by joshcalafell** [comment]
What reassurance do we have as a fallback if the database gets corrupted or erased ? What are your thoughts on this? We might keep it so that if this happens the dict could reload itself no?

**Comment by joshcalafell** [comment]
Closed this and separate this into two separate issues...
