### ISSUE TITLE
Engineer a pop up screen that lets you skip the intro from then on

### ISSUE THREAD

**Issue by joshcalafell** [rabbitfighter81/WordSleuth-Android#17]
As Stephen noted, going through this every time would be annoying, so we should let them have a notice before going to the search that says something like "never show this again".

**Comment by joshcalafell** [comment]
Maybe we could use a notification and shared preferences for this for persistence.

**Comment by redragonx** [comment]
An option screen would be nice.

**Comment by redragonx** [comment]
Changing the pop up window a little again. It does not need to be a question. The new window will have a okay button and the message: "This will only show once".

**Comment by joshcalafell** [comment]
Let's move this to after you skip the instructions. I think it would be better there... The we can close this issue.

**Comment by redragonx** [comment]
That won't be needed with the new popup. It wouldn't make sense then. Tell me if you still don't want it here.

**Comment by redragonx** [comment]
Closing for now.
