### ISSUE TITLE
Finish menu

### ISSUE THREAD

**Issue by joshcalafell** [rabbitfighter81/WordSleuth-Android#3]
No menu items work yet. These include
1) About menu item
2) Sort menu item
3) Overflow menu item
4) Save to list
5) Favorite
6) Share

**Comment by redragonx** [comment]
Remove the gear icon and info icon

**Comment by joshcalafell** [comment]
I removed the gear icon and info icon. But we need to plan our menu system next.

**Comment by joshcalafell** [comment]
Now we only want the go to instruction in the menu options.
