### ISSUE TITLE
Configure RateApp settings 

### ISSUE THREAD

**Issue by redragonx** [rabbitfighter81/WordSleuth-Android#30]
It needs a description, appstore link, and time parameters.

In SearchResultsFragment.java

**Comment by joshcalafell** [comment]
Let's give them more time I days. I would say that on the fifth start, or the 5th day as well. They might not have used it enough by two days. What do you think?

**Comment by joshcalafell** [comment]
If you think it's okay, I think it's okay. Close this at your discretion.
