### ISSUE TITLE
"Pimp this action bar!" 

### ISSUE THREAD

**Issue by joshcalafell** [rabbitfighter81/WordSleuth-Android#40]
Exactly that. Let's pimp out this action bar. I have a ton of images for android design icons, all with appropriate sizes  in mipmap folders. I spent a long time doing it right, so we could add what we need, and then take out what we don't use at the end. Anyway, any functionality you can think of or cool things we could do with the menu, let's do it... Also, read this:

<a href="http://developer.android.com/guide/topics/ui/actionbar.html">Android's Action Bar Stuff...</a>

**Comment by redragonx** [comment]
```
    <item
        android:id="@+id/dictionary_option"
        android:orderInCategory="2"
        app:showAsAction="never"
        android:title="@string/txt_dict_info" />
```

why do we care about dict info?

**Comment by joshcalafell** [comment]
Take it out. Unless we add another dictionary, we will have no use for explanation.

**Comment by redragonx** [comment]
okay. will do.
