### ISSUE TITLE
suggestion: about screen

### ISSUE THREAD

**Issue by redragonx** [rabbitfighter81/WordSleuth-Android#42]
Try it out in the search menu.

**Comment by joshcalafell** [comment]
Rad.

**Comment by joshcalafell** [comment]
Cool idea in the long run. I don't want either of our names in the app though, not that I think this is final or anything, just an F.Y.I.

**Comment by joshcalafell** [comment]
We could use this prototype for cool stuff! :)

**Comment by joshcalafell** [comment]
We dont need an about, we should remove it.
