### ISSUE TITLE
Add social media sharing

### ISSUE THREAD

**Issue by joshcalafell** [rabbitfighter81/WordSleuth-Android#5]
Add social media sharing

**Comment by redragonx** [comment]
What would we share?

**Comment by joshcalafell** [comment]
It would say something like I found that "Baron Cruelty" is an anagram for "Bryan Coulter" with WordSleuth(TM)

**Comment by redragonx** [comment]
http://stackoverflow.com/questions/9730243/how-to-filter-specific-apps-for-action-send-intent-and-set-a-different-text-for
